### ISSUE TITLE
Norton quarantine

### ISSUE THREAD

**Issue by vacsetron** [safex/safex_miner#4]
Norton anti-virus is pretty aggressive in putting this software in quarantine. I resolved it by trusting the software, but when I rebooted my pc it was blocked again. So I once managed to run it with mining in progress with a hash rate, but when it is blocked then the hash rate disappears and there is no mining.

**Comment by vacsetron** [comment]
Again I was taking the software out of quarantine, but still no hash rate. What worked for mee was just first to disable auto-protect, smart firewall, and breaching prevention in the Norton dashboard >> tab Security >> Advanced >> disable everything..... RUN the Safex-1-Click-Miner... (yes you have a hash rate now!) and then enable your security again on the Norton Dashboard. Good luck guys and don't forget to trust the software so users in the future will have fewer problems.

**Comment by atanmarko** [comment]
@vacsetron thanks for info! New version of Safex-1-Click-Miner with cryptonight-v8 algorithm mining should be out next week so we will try to workaround this.

**Comment by ddabek** [comment]
this GUI comes stock with mining software, which is flagged in case it is malicious. We sign our releases with Safex Developers doo; so be sure the check the signature of the binary as well just to be sure it is the one we officially released.
